### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by cdoky** [web3ToolBoxDev/toolBoxClient#2]
```
➜  toolBoxClient git:(main) ✗ yarn dist
Debugger attached.
yarn run v1.22.19
warning ../../package.json: No license field
$ electron-builder
Debugger attached.
  • electron-builder  version=24.12.0 os=23.4.0
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=/Users/cc/WorkSpace/toolBoxClient/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=arm64 electron=29.0.1 appOutDir=dist/mac-arm64
  • signing         file=dist/mac-arm64/web3toolbox.app platform=darwin type=distribution identity=600847F1EB09A6787E9F644D7F1239BCC98D12F2 provisioningProfile=none
  ⨯ ENOENT: no such file or directory, stat '/Users/cc/WorkSpace/toolBoxClient/dist/mac-arm64/web3toolbox.app/Contents/Resources/assets/node_for_mac/node-v21.6.2-mac/bin/corepack'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, stat '/Users/cc/WorkSpace/toolBoxClient/dist/mac-arm64/web3toolbox.app/Contents/Resources/assets/node_for_mac/node-v21.6.2-mac/bin/corepack'
    at processImmediate (node:internal/timers:478:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
From previous event:
    at readDirectoryAndSign (/Users/cc/WorkSpace/toolBoxClient/node_modules/app-builder-lib/src/macPackager.ts:472:29)
    at MacPackager.signApp (/Users/cc/WorkSpace/toolBoxClient/node_modules/app-builder-lib/src/macPackager.ts:482:11)
    at MacPackager.doSignAfterPack (/Users/cc/WorkSpace/toolBoxClient/node_modules/app-builder-lib/src/platformPackager.ts:332:21)
    at MacPackager.doPack (/Users/cc/WorkSpace/toolBoxClient/node_modules/app-builder-lib/src/platformPackager.ts:317:7)
    at MacPackager.pack (/Users/cc/WorkSpace/toolBoxClient/node_modules/app-builder-lib/src/macPackager.ts:192:9)
    at Packager.doBuild (/Users/cc/WorkSpace/toolBoxClient/node_modules/app-builder-lib/src/packager.ts:442:9)
    at executeFinally (/Users/cc/WorkSpace/toolBoxClient/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/cc/WorkSpace/toolBoxClient/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/cc/WorkSpace/toolBoxClient/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/cc/WorkSpace/toolBoxClient/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
![image](https://github.com/web3ToolBoxDev/toolBoxClient/assets/626401/d6865224-9f6f-4711-87cc-3feef1633c08)

**Comment by web3ToolBoxDev** [comment]
IS_BUILD前面加上const试试，好像上个版本提交的代码漏掉了

**Comment by cdoky** [comment]
@web3ToolBoxDev 还是不行
![image](https://github.com/web3ToolBoxDev/toolBoxClient/assets/626401/949b0db9-37a0-4ed5-9e76-9ae8d5b3428f)
` • loaded configuration  file=package.json ("build" field)`会是这里的问题吗？

**Comment by cdoky** [comment]
找到问题了

![image](https://github.com/web3ToolBoxDev/toolBoxClient/assets/626401/b75ea5a3-b816-4905-8b15-d8b54443845f)

这几个软连接, 都找不到目录文件, 所以导致打包失败

**Comment by web3ToolBoxDev** [comment]
👌
